### ISSUE TITLE
Seg fault in zlib caused by fiona

### ISSUE THREAD

**Issue by j-t-t** [conda-forge/fiona-feedstock#154] opened 2019-12-02 15:47 UTC
Issue:
Seg fault when the following is run in a python terminal
```
import fiona
import zlib
zlib.compress(b"test")
```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/jenny/anaconda3/envs/crash-model:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
astroid                   2.3.3                    py36_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.13.2           py36h8022711_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
codecov                   2.0.15                     py_1    conda-forge
coverage                  4.5.4            py36h516909a_0    conda-forge
cryptography              2.8              py36h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fiona                     1.8.11           py36h900e953_0    conda-forge
flask                     1.1.1                      py_1    conda-forge
folium                    0.10.0                     py_1    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
future                    0.18.2                   py36_0    conda-forge
gdal                      3.0.2            py36hbb6b9fb_5    conda-forge
geocoder                  1.38.1                     py_1    conda-forge
geographiclib             1.50                       py_0    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.6.2                      py_0    conda-forge
geopy                     1.20.0                     py_0    conda-forge
geos                      3.8.0                he1b5a44_0    conda-forge
geotiff                   1.5.1                hbd99317_7    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3          py36h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py36_1000    conda-forge
importlib_metadata        1.1.0                    py36_0    conda-forge
ipdb                      0.12.2                     py_0    conda-forge
ipykernel                 5.1.3            py36h5ca1d4c_0    conda-forge
ipython                   7.10.1           py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.2.1                    py36_1    conda-forge
isort                     4.3.21                   py36_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.15.1                   py36_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
joblib                    0.14.0                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.2.0                    py36_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.3                    py36_1    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.6.1                    py36_0    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
lazy-object-proxy         1.4.3            py36h516909a_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.0           default_hde54327_4    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libgdal                   3.0.2                h30a29e3_5    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm9                  9.0.0                hc9558a2_3    conda-forge
libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
libopenblas               0.3.7                h5ec1e0e_4    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_2    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_1    conda-forge
libspatialite             4.3.0a            h343d7df_1033    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
libtiff                   4.1.0                hc3755c2_1    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                hf4e8a37_4    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxgboost                0.90                 he1b5a44_4    conda-forge
libxkbcommon              0.9.1                hebb1f50_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py36h516909a_0    conda-forge
matplotlib                3.1.2                    py36_1    conda-forge
matplotlib-base           3.1.2            py36h250f245_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py36h516909a_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbconvert                 5.6.1                    py36_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
notebook                  6.0.1                    py36_0    conda-forge
nspr                      4.23                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.17.3           py36h95a1406_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openpyxl                  3.0.2                      py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
osmnx                     0.10                       py_1    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.3           py36hb3f55d8_0    conda-forge
pandoc                    2.8.0.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       19.3.1                   py36_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_2    conda-forge
proj                      6.2.1                hc80f0dc_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            3.0.2                      py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
py-xgboost                0.90                     py36_4    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pylint                    2.4.4                    py36_0    conda-forge
pyopenssl                 19.1.0                   py36_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
pyproj                    2.4.2.post1      py36h12732c1_0    conda-forge
pyqt                      5.12.3           py36hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.6           py36h516909a_0    conda-forge
pysocks                   1.7.1                    py36_0    conda-forge
pytest                    5.3.1                    py36_0    conda-forge
pytest-cov                2.8.1                      py_0    conda-forge
python                    3.6.7             h357f687_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py36h516909a_1    conda-forge
pyzmq                     18.1.1           py36h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
ratelim                   0.1.6                      py_2    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
rtree                     0.9.1            py36h7b0cdae_0    conda-forge
ruamel.yaml               0.16.5           py36h516909a_1    conda-forge
ruamel.yaml.clib          0.2.0            py36h516909a_0    conda-forge
scikit-learn              0.21.3           py36hcdab131_0    conda-forge
scipy                     1.3.2            py36h921218d_0    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                42.0.2                   py36_0    conda-forge
shapely                   1.6.4           py36h5d51c17_1007    conda-forge
six                       1.13.0                   py36_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
statsmodels               0.10.2           py36hc1659b7_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
terminado                 0.8.3                    py36_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.3            py36h516909a_0    conda-forge
traitlets                 4.3.3                    py36_0    conda-forge
typed-ast                 1.4.0            py36h516909a_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
tzlocal                   2.0.0                      py_0    conda-forge
urllib3                   1.25.7                   py36_0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.0                     py_0    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
widgetsnbextension        3.2.1                    py36_0    conda-forge
wrapt                     1.11.2           py36h516909a_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                he1b5a44_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : crash-model
    active env location : /home/jenny/anaconda3/envs/crash-model
            shell level : 1
       user config file : /home/jenny/.condarc
 populated config files : 
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/jenny/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jenny/anaconda3/pkgs
                          /home/jenny/.conda/pkgs
       envs directories : /home/jenny/anaconda3/envs
                          /home/jenny/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-69-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/jenny/.netrc
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment] 2019-12-02 16:51
I cannot reproduce that with a fresh environment using python 3.6 and fiona.

```python
In [1]: import fiona 
   ...: import zlib 
   ...: zlib.compress(b"test")                                                                
Out[1]: b'x\x9c+I-.\x01\x00\x04]\x01\xc1'
```

```
> conda list
# packages in environment at /home/filipe/miniconda3/envs/TEST:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fiona                     1.8.11           py36h900e953_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      3.0.2            py36hbb6b9fb_5    conda-forge
geos                      3.8.0                he1b5a44_0    conda-forge
geotiff                   1.5.1                hbd99317_7    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3          py36h6f030ca_1002    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
ipython                   7.10.1           py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.1                   py36_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libgdal                   3.0.2                h30a29e3_5    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
libopenblas               0.3.7                h5ec1e0e_4    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_2    conda-forge
libspatialite             4.3.0a            h343d7df_1033    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
libtiff                   4.1.0                hc3755c2_1    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                hf4e8a37_4    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
munch                     2.5.0                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.3           py36h95a1406_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
parso                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       19.3.1                   py36_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_2    conda-forge
proj                      6.2.1                hc80f0dc_0    conda-forge
prompt_toolkit            3.0.2                      py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.5.2                      py_0    conda-forge
python                    3.6.7             h357f687_1006    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                42.0.2                   py36_0    conda-forge
shapely                   1.6.4           py36h5d51c17_1007    conda-forge
six                       1.13.0                   py36_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
traitlets                 4.3.3                    py36_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```

Also, it is highly unlikely this is `fiona`'s fault. If you can narrow down to a minim environment that reproduces the problem let me know. Closing this for now b/c there is nothing we can do with `fiona` to fix what you are experiencing.

**Comment by j-t-t** [comment] 2019-12-02 18:57
To reproduce, create a file called `Dockerfile` with the following
```Dockerfile
FROM continuumio/miniconda3

RUN conda install -y fiona
RUN python -c "import fiona; import zlib; zlib.compress(b'test')"
```
and then do `docker build .` in the directory where the Dockerfile is.

If you leave the fiona import out, it won't segfault

**Comment by ocefpaf** [comment] 2019-12-02 20:45
I'm not familiar with that docker image but I cannot reproduce that on my Linux machine, so I believe it is something specific to the docker image. I would raise an issue on the docker image repository (if that exists).

**Comment by jorisvandenbossche** [comment] 2019-12-02 20:47
Just tried, and I can actually reproduce this on my linux machine.

What I did:

```
conda create -n test-fiona-segfault python=3.6
conda activate test-fiona-segfault
conda install fiona
```

and then `python -c "import fiona; import zlib; zlib.compress(b'test')"` segfaults. While removing the fiona import is fine.

**Comment by j-t-t** [comment] 2019-12-02 20:58
I was running it in on my linux machine originally. I just made the docker image to see if that would make it easier to replicate (and to eliminate the possibility that I had a cached conda package causing the issue). But I see that @jorisvandenbossche was able to replicate as well.

**Comment by ocefpaf** [comment] 2019-12-02 21:30
> Just tried, and I can actually reproduce this on my linux machine (without docker).

What linux are you using? Is your `conda list` the same as @j-t-t? I
I just tried that again but I notice one difference. I tested that inside IPython, where the segfault does not happen! That is quite odd.

**Comment by jorisvandenbossche** [comment] 2019-12-02 21:34
Hmm, indeed in IPython it does not happen ...

> What linux are you using?

Ubuntu 18.04

**Comment by jorisvandenbossche** [comment] 2019-12-03 09:48
@ocefpaf do you also see it in plain python console?

**Comment by ocefpaf** [comment] 2019-12-03 12:43
> @ocefpaf do you also see it in plain python console?

Yep. It fails there too.

**Comment by akrherz** [comment] 2021-12-01 20:47
I am not seeing this currently on python3.8 + linux 64

```
>>> import fiona; import zlib; zlib.compress(b'test')
b'x\x9c+I-.\x01\x00\x04]\x01\xc1'
```

Assuming this is no longer an issue, can reopen if somebody has a current reproducer!

**Closed by akrherz** 2021-12-01 20:47 UTC
