### ISSUE TITLE
ImportError with Fiona when importing GeoPandas

### ISSUE THREAD

**Issue by rrpelgrim** [conda-forge/fiona-feedstock#172] opened 2020-11-03 14:43 UTC
Issue:

When I try to convert the geometry of a geodataframe in Jupyter Notebook running Python 3, my kernel keeps dying. When I run the minimal reproducible code in a python terminal script, I get the following output which points to an issue with Fiona.

StackOverflow question [here](https://stackoverflow.com/questions/64663553/kernel-dying-when-executing-to-crs-to-convert-geometry-of-geodataframe).

Minimal reproducible code:
```
df = pd.DataFrame(
    {'City': ['A', 'B', 'C', 'D', 'E'],
     'Country': ['1', '2', '3', '4', '5'],
     'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
     'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})

crs = {'init': 'epsg:4326'}

gdf = gpd.GeoDataFrame(
    df, crs=crs, geometry=gpd.points_from_xy(df.Longitude, df.Latitude))

gdf.geometry = gdf.geometry.to_crs(epsg=3857)
```

```
(geo) RichardgrimsMBP:desktop data_science$ python tocrs.py
Traceback (most recent call last):
File "tocrs.py", line 4, in
import geopandas as gpd
File "/opt/anaconda3/envs/geo/lib/python3.8/site-packages/geopandas/init.py", line 7, in
from geopandas.io.file import _read_file as read_file # noqa
File "/opt/anaconda3/envs/geo/lib/python3.8/site-packages/geopandas/io/file.py", line 7, in
import fiona
File "/opt/anaconda3/envs/geo/lib/python3.8/site-packages/fiona/init.py", line 86, in
from fiona.collection import BytesCollection, Collection
File "/opt/anaconda3/envs/geo/lib/python3.8/site-packages/fiona/collection.py", line 11, in
from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/opt/anaconda3/envs/geo/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 2): Symbol not found: _CCCryptorGCMFinalize
Referenced from: /opt/anaconda3/envs/geo/lib/libtiledb.dylib (which was built for Mac OS X 10.13)
Expected in: /usr/lib/libSystem.B.dylib
in /opt/anaconda3/envs/geo/lib/libtiledb.dylib
```

<br/>
Environment (<code># packages in environment at /opt/anaconda3/envs/geo:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0           py38h32f6830_1002    conda-forge
argon2-cffi               20.1.0           py38h4d0b108_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
boost-cpp                 1.74.0               he5d75e3_0    conda-forge
bzip2                     1.0.8                haf1e3a3_3    conda-forge
c-ares                    1.16.1               haf1e3a3_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            h360c52f_1006    conda-forge
certifi                   2020.6.20        py38h5347e94_2    conda-forge
cffi                      1.14.3           py38h9edaa1b_1    conda-forge
cfitsio                   3.470                h4472c5d_7    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.0                      py_0    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
entrypoints               0.3             py38h32f6830_1002    conda-forge
expat                     2.2.9                hb1e8313_2    conda-forge
fiona                     1.8.17           py38hcfd527e_1    conda-forge
fontconfig                2.13.1            h79c0d67_1002    conda-forge
freetype                  2.10.4               h3f75d11_0    conda-forge
freexl                    1.0.5             h0b31af3_1002    conda-forge
gdal                      3.1.4            py38hdf98abe_0    conda-forge
geopandas                 0.8.1                      py_0    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.6.0                hc1004f4_3    conda-forge
gettext                   0.19.8.1          haf92f58_1004    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.66.2               h4961a3e_0    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.6          nompi_h2ccf146_1110    conda-forge
icu                       67.1                 hb1e8313_0    conda-forge
importlib-metadata        2.0.0                      py_1    conda-forge
importlib_metadata        2.0.0                         1    conda-forge
ipykernel                 5.3.4            py38h1cdfbd6_1    conda-forge
ipython                   7.19.0           py38h9bb44b7_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.2           py38h32f6830_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
json-c                    0.13.1            h575e443_1002    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_2    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kealib                    1.4.13               h40102fb_1    conda-forge
kiwisolver                1.3.1            py38h9250c2b_0    conda-forge
krb5                      1.17.1               h75d18d8_3    conda-forge
lcms2                     2.11                 h174193d_0    conda-forge
libblas                   3.9.0                2_openblas    conda-forge
libcblas                  3.9.0                2_openblas    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libdap4                   3.20.6               h993cace_1    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgdal                   3.1.4                hd7bf8dc_0    conda-forge
libgfortran               5.0.0               h7cc5361_13    conda-forge
libgfortran5              9.3.0               h7cc5361_13    conda-forge
libglib                   2.66.2               h2fc9090_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h8ca2c65_1012    conda-forge
liblapack                 3.9.0                2_openblas    conda-forge
libnetcdf                 4.7.4           nompi_h4844aed_106    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     12.3                 haa216e0_2    conda-forge
libsodium                 1.0.18               haf1e3a3_1    conda-forge
libspatialindex           1.9.3                h4a8c4bd_3    conda-forge
libspatialite             5.0.0                hc85de81_0    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
libxml2                   2.9.10               h2c6e4a5_2    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
lz4-c                     1.9.2                hb1e8313_3    conda-forge
markupsafe                1.1.1            py38h94c058a_2    conda-forge
matplotlib                3.3.2            py38h32f6830_1    conda-forge
matplotlib-base           3.3.2            py38had0acaf_1    conda-forge
mistune                   0.8.4           py38h4d0b108_1002    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py38h32f6830_2    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
ncurses                   6.2                  hb1e8313_2    conda-forge
nest-asyncio              1.4.2              pyhd8ed1ab_0    conda-forge
notebook                  6.1.4            py38h32f6830_1    conda-forge
numpy                     1.19.2           py38ha98150c_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.3.1                h254dc36_3    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.4            py38hcf432d8_0    conda-forge
pandoc                    2.11.0.4             h22f3db7_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py38hef457fe_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
poppler                   0.89.0               h3232a60_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 hb1f69c7_2    conda-forge
proj                      7.1.1                h45baca5_3    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.8                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.2                      py_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38h4367d1d_3    conda-forge
pyrsistent                0.17.3           py38h4d0b108_1    conda-forge
python                    3.8.6           hcfdab8c_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
pyzmq                     19.0.2           py38h2c785a9_2    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
rtree                     0.9.4            py38h08f867b_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h5347e94_2    conda-forge
shapely                   1.7.1            py38h8918236_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
terminado                 0.9.1            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tiledb                    2.1.2                h73727fa_0    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
tornado                   6.1              py38h7e3306e_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tzcode                    2020a                h0b31af3_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xerces-c                  3.2.3                h0a0444a_1    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.3                hb1e8313_2    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.5                h289c70a_2    conda-forge</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code> (geo) RichardgrimsMBP:springboard_repo data_science$ conda info

     active environment : geo
    active env location : /opt/anaconda3/envs/geo
            shell level : 2
       user config file : /Users/data_science/.condarc
 populated config files : /Users/data_science/.condarc
          conda version : 4.9.1
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __osx=10.11.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/data_science/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/data_science/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.1 requests/2.24.0 CPython/3.7.4 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False </code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment] 2020-11-03 14:52
Can you try:

```
conda create --name TMP  python=3.8 geopandas --yes
conda activate TMP
python -c "import fiona; print(fiona.__version__)"
```

I cannot see any problem with your package list but let's try a new env without any pre-existing packages just to be sure.

**Comment by rrpelgrim** [comment] 2020-11-03 15:07
Thanks. Output from terminal below:

(TMP) Richard-Pelgrims-MacBook-Pro:~ data_science$ python -c "import fiona; print(fiona.__version__)"
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/TMP/lib/python3.8/site-packages/fiona/__init__.py", line 86, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/opt/anaconda3/envs/TMP/lib/python3.8/site-packages/fiona/collection.py", line 11, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/opt/anaconda3/envs/TMP/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 2): Symbol not found: _CCCryptorGCMFinalize
  Referenced from: /opt/anaconda3/envs/TMP/lib/libtiledb.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /opt/anaconda3/envs/TMP/lib/libtiledb.dylib```

**Comment by ocefpaf** [comment] 2020-11-03 15:11
I don't have a macOS to test but that works for me on Linux with the same packages. In the past we saw issues with some systems packages, like geos from brew, which interfered with the conda installation. I'll ask around for someone with a macOS to test this to be sure it is not the packages.

**Comment by rrpelgrim** [comment] 2020-11-03 15:18
Alright, thanks for your help. Please let me know if you find out more.

**Comment by ocefpaf** [comment] 2020-11-04 11:18
@isuruf sorry to bother you with macOS issues but this part of the error:

```
Referenced from: /opt/anaconda3/envs/TMP/lib/libtiledb.dylib (which was built for Mac OS X 10.13)
```

makes me thing it has something to do with the new SDK. Does something need to be rebuilt?

**Comment by isuruf** [comment] 2020-11-04 16:08
newer tiledb requires macOS >=10.13. When the system is older (10.11 in this case), conda solver wouldn't install these newer versions of tiledb. Can you try creating a new environment?

**Comment by ocefpaf** [comment] 2020-11-04 16:10
> Can you try creating a new environment?

I asked in https://github.com/conda-forge/fiona-feedstock/issues/172#issuecomment-721166880. Looks like it did not help, right @rrpelgrim? Maybe you can try again ensuring you are copying and pasting the exact commands?

**Comment by isuruf** [comment] 2020-11-04 16:24
nvm, this seems to be a bug in conda solver. `mamba` doesn't install tiledb=2.1.2

To reproduce in linux
```
export CONDA_OVERRIDE_OSX=10.11
CONDA_SUBDIR=osx-64 conda create --name TMP  python=3.8 geopandas --dry-run   # installs tiledb=2.1.2
CONDA_SUBDIR=osx-64 mamba create --name TMP  python=3.8 geopandas --dry-run  # installs tiledb=2.0.8
```

**Comment by chenghlee** [comment] 2020-11-04 17:17
Originated from [this comment](https://github.com/conda-forge/fiona-feedstock/issues/172#issuecomment-721832525) on the conda-forge fiona-feedstock.

**Comment by rrpelgrim** [comment] 2020-11-04 18:24
Thanks for verifying @isuruf. Should I follow progress on [the new issue](https://github.com/conda/conda/issues/10334) on conda to find out how to resolve this?

**Comment by ocefpaf** [comment] 2020-11-04 18:30
@rrpelgrim at the moment you can try to pin an older version of `tiledb` until we fix this at either a conda level or a packaging level.

**Comment by rrpelgrim** [comment] 2020-11-05 10:10
@ocefpaf thanks, tiledb version 2.0.8 did the trick for me. Kernel no longer dying. Thanks so much for your time 🙏

**Comment by ocefpaf** [comment] 2020-11-05 14:12
> @ocefpaf thanks, tiledb version 2.0.8 did the trick for me. Kernel no longer dying. Thanks so much for your time

No problem. We are working on short and long term plans to fix this. Going from correcting the packages that are wrongly targeting the newer SDK to improve solvabilidade in conda to ensure the right one is always installed.

Closing this b/c we are tracking it in conda and our docs now. Thanks for the report!

**Closed by ocefpaf** 2020-11-05 14:12 UTC

**Comment by isuruf** [comment] 2020-11-06 22:45
@ocefpaf, can you open an issue in `tiledb` or send a PR?

**Comment by ocefpaf** [comment] 2020-11-06 23:07
> @ocefpaf, can you open an issue in `tiledb` or send a PR?

I can send a PR to fix it. I recall you sending me what needs to be fixed but I lost it :-/
Do you mind sending it again?
