### ISSUE TITLE
Cannot import fiona via geopandas

### ISSUE THREAD

**Issue by najascutellatus** [conda-forge/fiona-feedstock#82] opened 2018-06-29 16:39 UTC
I created a condaenv using geopandas yesterday and it worked fine. At some point today, I needed to create a new conda env and now I'm getting an ImportError for fiona when I import geopandas. I'm using all conda-forge packages.
 
I'll post code snippets below.

I'm using OSX 10.13.4

$ conda create --name geopandas python=3.6 geopandas
$ conda activate geopandas
$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
>>> import geopandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mikesmith/miniconda3/envs/geopandas/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/Users/mikesmith/miniconda3/envs/geopandas/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/Users/mikesmith/miniconda3/envs/geopandas/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/mikesmith/miniconda3/envs/geopandas/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/mikesmith/miniconda3/envs/geopandas/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libhdf5_cpp.102.dylib
  Referenced from: /Users/mikesmith/miniconda3/envs/geopandas/lib/libkea.1.4.dylib
  Reason: image not found
>>>

$ conda list
# packages in environment at /Users/mikesmith/miniconda3/envs/geopandas:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    conda-forge
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
click                     6.7                        py_1    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
curl                      7.60.0               h93b3f91_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
descartes                 1.1.0                      py_1    conda-forge
expat                     2.2.5                         0    conda-forge
fiona                     1.7.12                   py36_0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
freexl                    1.0.5                         0    conda-forge
gdal                      2.2.4                    py36_0    conda-forge
geopandas                 0.3.0                    py36_0    conda-forge
geos                      3.6.2                hfc679d8_2    conda-forge
geotiff                   1.4.2                hb54a4aa_1    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.55.0                        0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
jpeg                      9b                            2    conda-forge
json-c                    0.12.1                        0    conda-forge
kealib                    1.4.9                hfc679d8_1    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
krb5                      1.14.6                        0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.2.4                         4    conda-forge
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.15                 h470a237_1    conda-forge
libkml                    1.3.0                         6    conda-forge
libnetcdf                 4.6.1                         2    conda-forge
libpng                    1.6.34                        0    conda-forge
libpq                     9.6.3                         0    conda-forge
libspatialindex           1.8.5                hfc679d8_2    conda-forge
libspatialite             4.3.0a                       19    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_0    conda-forge
libxml2                   2.9.8                         0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.14.5          py36_blas_openblash24bf2e0_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0                         2    conda-forge
openssl                   1.0.2o                        0    conda-forge
pandas                    0.23.1                   py36_0    conda-forge
pcre                      8.41                          1    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
poppler                   0.61.1                        3    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
psycopg2                  2.7.5                    py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pysal                     1.14.3                   py36_0    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
readline                  7.0                           0    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
scipy                     1.1.0           py36_blas_openblas_200  [blas_openblas]  conda-forge
setuptools                39.2.0                   py36_0    conda-forge
shapely                   1.6.4            py36h164cb2d_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlalchemy                1.2.8                    py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

**Comment by ocefpaf** [comment] 2018-06-29 18:30
Working on it. When the new `libgdal` build is done things should be OK for `fiona`. Hold on...

**Comment by ocefpaf** [comment] 2018-06-29 20:56
I'm closing as a duplicate of https://github.com/conda-forge/gdal-feedstock/issues/209 (just to make it easier to track in one place).

Things should be OK as soon as I finish to rebuild the stack with `hdf 1.10.2`. (But it will take a while...)

**Closed by ocefpaf** 2018-06-29 20:56 UTC
