### ISSUE TITLE
Error importing GeoPandas: 'image not found'

### ISSUE THREAD

**Issue by mmaari** [conda-forge/fiona-feedstock#128] opened 2019-04-15 08:11 UTC
HI!
I am relatively new to Python and GeoPandas. I am having an issue importing the GeoPandas package which has already been raised but still not solved for me.
I have created an environment with only conda-forge packages, installed fiona and geopandas in there and working in the environment on Jupyter Notebook. I still get the same error message when I do 

```
import geopandas as pd
```

Namely, the error message is this: 

```
ImportError                               Traceback (most recent call last)
<ipython-input-2-a62d01c1d62e> in <module>
----> 1 import geopandas as gpd

~/anaconda3/lib/python3.7/site-packages/geopandas/__init__.py in <module>
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

~/anaconda3/lib/python3.7/site-packages/geopandas/io/file.py in <module>
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 import six

~/anaconda3/lib/python3.7/site-packages/fiona/__init__.py in <module>
     81     os.environ["PATH"] = os.environ["PATH"] + ";" + libdir
     82 
---> 83 from fiona.collection import BytesCollection, Collection
     84 from fiona.drvsupport import supported_drivers
     85 from fiona.env import ensure_env_with_credentials, Env

~/anaconda3/lib/python3.7/site-packages/fiona/collection.py in <module>
      7 
      8 from fiona import compat, vfs
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import buffer_to_virtual_file, remove_virtual_file, GEOMETRY_TYPES

ImportError: dlopen(/anaconda3/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libgif.7.dylib
  Referenced from: /anaconda3/lib/libgdal.20.dylib
  Reason: image not found
```
and when running
```
conda list
```
I get this: 
```
# packages in environment at /anaconda3/envs/env2:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            h9247486_1000    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.64.1               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
descartes                 1.1.0                      py_3    conda-forge
expat                     2.2.5             h0a44026_1002    conda-forge
fiona                     1.8.6            py37h7eb7563_2    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      2.4.1            py37h7eb7563_0    conda-forge
geopandas                 0.4.1                      py_1    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
geotiff                   1.4.3             hce09ea4_1000    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h2836805_1001    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            hecf890f_1003    conda-forge
kiwisolver                1.0.1           py37h04f5b5a_1002    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    8.0.0                         2    conda-forge
libcxxabi                 8.0.0                         2    conda-forge
libdap4                   3.19.1            hae55d67_1000    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   2.4.1                h16bfee5_0    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             h71ee1b2_1009    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.36            ha441bb4_1000    conda-forge
libpq                     11.2                 h29c6f28_0    conda-forge
libspatialindex           1.9.0                h6de7cb9_0    conda-forge
libspatialite             4.3.0a            h0cd9627_1026    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            h344961e_1002    conda-forge
libxml2                   2.9.8             hf14e9c8_1005    conda-forge
mapclassify               2.0.1                      py_0    conda-forge
matplotlib                3.0.3                    py37_0    conda-forge
matplotlib-base           3.0.3            py37hf043ca5_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.16.2           py37hbb3c62a_1    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openjpeg                  2.3.1                hc1feee7_0    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
pandas                    0.24.2           py37h0a44026_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pixman                    0.34.0            h1de35cc_1003    conda-forge
poppler                   0.67.0               hb974355_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.2                 h16efa30_0    conda-forge
proj4                     5.2.0             h1de35cc_1001    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py37h9c430a6_1000    conda-forge
python                    3.7.3                h0d93f26_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
rtree                     0.8.3           py37h666c49c_1002    conda-forge
scipy                     1.2.1            py37hbd7caa9_1    conda-forge
setuptools                41.0.0                   py37_0    conda-forge
shapely                   1.6.4           py37h4b8df73_1003    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0            h1765d9f_1001    conda-forge
tk                        8.6.9             ha441bb4_1001    conda-forge
tornado                   6.0.2            py37h01d97ff_0    conda-forge
tzcode                    2018g             h1de35cc_1001    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xerces-c                  3.2.2             h44e365a_1001    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.3.3                         1    conda-forge
```
I am using macOS Mojave version 10.14.3

Anyone knows how to help me? I would be very grateful!

Thank you!

**Comment by ocefpaf** [comment] 2019-04-15 11:01
Please ensure that your [`.condarc`](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html) has the following configuration , the `conda-forge` channel on top of `defaults` and the `strict` channel option enabled:


```
channel_priority: strict
channels:
  - conda-forge
  - defaults
```

Then try,

```
conda create --name TEST python=3.7 geopandas
conda activate TEST
python -c "import geopandas; print(geopandas.__version__)"
```

If that does not work we will need help fro m someone that has a macOS to test this. Everything works as expected on Linux.

**Comment by mmaari** [comment] 2019-04-17 08:07
Thank you very much @ocefpaf for your help. 
I have tried it, but unfortunately it is still not working. 

I report here again the output of
```
conda list 
```
in case it helps. 
```
# packages in environment at /anaconda3/envs/TEST:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            h9247486_1000    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.64.1               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
descartes                 1.1.0                      py_3    conda-forge
expat                     2.2.5             h0a44026_1002    conda-forge
fiona                     1.8.6            py37h7eb7563_2    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      2.4.1            py37h7eb7563_0    conda-forge
geopandas                 0.4.1                      py_1    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
geotiff                   1.4.3             hce09ea4_1000    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h2836805_1001    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            hecf890f_1003    conda-forge
kiwisolver                1.0.1           py37h04f5b5a_1002    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0                5_openblas    conda-forge
libcblas                  3.8.0                5_openblas    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    8.0.0                         2    conda-forge
libcxxabi                 8.0.0                         2    conda-forge
libdap4                   3.19.1            hae55d67_1000    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   2.4.1                h16bfee5_0    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             h71ee1b2_1009    conda-forge
liblapack                 3.8.0                5_openblas    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     11.2                 h29c6f28_0    conda-forge
libspatialindex           1.9.0                h6de7cb9_0    conda-forge
libspatialite             4.3.0a            h0cd9627_1026    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            h344961e_1002    conda-forge
libxml2                   2.9.8             hf14e9c8_1005    conda-forge
mapclassify               2.0.1                      py_0    conda-forge
matplotlib                3.0.3                    py37_0    conda-forge
matplotlib-base           3.0.3            py37hf043ca5_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.16.2           py37hbb3c62a_1    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openjpeg                  2.3.1                hc1feee7_0    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
pandas                    0.24.2           py37h0a44026_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pixman                    0.34.0            h1de35cc_1003    conda-forge
poppler                   0.67.0               hb974355_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.2                 h16efa30_0    conda-forge
proj4                     5.2.0             h1de35cc_1001    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py37h9c430a6_1000    conda-forge
python                    3.7.3                h0d93f26_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
rtree                     0.8.3           py37h666c49c_1002    conda-forge
scipy                     1.2.1            py37hbd7caa9_1    conda-forge
setuptools                41.0.0                   py37_0    conda-forge
shapely                   1.6.4           py37h4b8df73_1003    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0            h1765d9f_1001    conda-forge
tk                        8.6.9             ha441bb4_1001    conda-forge
tornado                   6.0.2            py37h01d97ff_0    conda-forge
tzcode                    2018g             h1de35cc_1001    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xerces-c                  3.2.2             h44e365a_1001    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.3.3                         1    conda-forge
```

I am thankful for any help.

**Comment by ocefpaf** [comment] 2019-04-18 15:37
@mmaari I rebuilt gdal in https://github.com/conda-forge/gdal-feedstock/pull/280 and fiona in https://github.com/conda-forge/fiona-feedstock/pull/129 but I could not reproduce the problem you are seeing with the CIs and I don't have a mac to test it further than the CI builds :-/

Can you try again and see if the rebuilds helped with your problem?

**Comment by Joe-Heffer-MPE** [comment] 2019-05-20 11:06
Is this the cause of the problem?

> We strongly recommend to either install everything from the defaults channel, or everything from the conda-forge channel. Ending up with a mixture of packages from both channels for the dependencies of GeoPandas can lead to import problems. See the conda-forge section on using multiple channels for more details.

http://geopandas.org/install.html#using-the-conda-forge-channel

**Comment by ocefpaf** [comment] 2019-05-20 12:00
Closing this b/c I cannot reproduce it using the recommended install instructions. Please re-open if you are still experiencing the problem.

**Closed by ocefpaf** 2019-05-20 12:00 UTC
