### ISSUE TITLE
Cannot import Fiona and GeoPandas to Jupyter Notebook

### ISSUE THREAD

**Issue by yutingwum** [conda-forge/fiona-feedstock#80] opened 2018-06-08 03:48 UTC
Hi I tried to import GeoPandas to Jupyter noteboook but did not work. The import error tells me it is related to Fiona. I installed GeoPandas and its dependencies through conda install. Any help is appreciated!

The error looks like this:
![image](https://user-images.githubusercontent.com/23270584/41138155-53da005c-6aad-11e8-9fda-0324627bb2c1.png)

This is my packages:
![image](https://user-images.githubusercontent.com/23270584/41138142-3fc23a08-6aad-11e8-8ff5-d6089ac006a6.png)

**Comment by ocefpaf** [comment] 2018-06-08 11:27
Closing as duplicate of https://github.com/conda-forge/geopandas-feedstock/issues/38#issuecomment-395638224

Please do not open multiple issue. It is taxing on the maintainers.

**Closed by ocefpaf** 2018-06-08 11:27 UTC
