### ISSUE TITLE
"Reason: image not found" error for OS X 10.11, Anaconda 3.5.1

### ISSUE THREAD

**Issue by dannguyen** [conda-forge/fiona-feedstock#13] opened 2016-05-16 21:11 UTC
On OS X 10.11.4, using Anaconda:

            3.5.1 |Anaconda 2.5.0 (x86_64)| (default, Dec  7 2015, 11:24:55) 
            [GCC 4.2.1 (Apple Inc. build 5577)]

Entirety of the error message -- it breaks upon `import fiona`:

~~~
ImportError                               Traceback (most recent call last)
<ipython-input-9-cc872b235141> in <module>()
----> 1 import fiona

/Users/dtown/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv, supported_drivers
     71 from fiona.odict import OrderedDict

/Users/dtown/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/fiona/collection.py in <module>()
      5 import sys
      6 
----> 7 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
      8 from fiona.ogrext import Session, WritingSession
      9 from fiona.ogrext import (

ImportError: dlopen(/Users/dtown/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libmfhdf.0.dylib
  Referenced from: /Users/dtown/.pyenv/versions/anaconda3-2.5.0/lib/libgdal.1.dylib
  Reason: image not found
~~~

**Comment by ocefpaf** [comment] 2016-05-17 14:03
Please try the lines below to help me debug this:

```shell
conda create -n test_fiona python=3.5 fiona --yes -c conda-forge
source activate test_fiona
python -c "import fiona; print(fiona.__version__)"
conda list
```

If the 3rd line fails please copy and paste the result of `conda list` here.

**Comment by dannguyen** [comment] 2016-05-17 20:30
Strange...something seems to be wrong with the environment-building code (sorry, I don't use virtualenv or conda's equivalent of it, so I don't have the fix off-hand, but FYI):

```
$ source activate test_fiona
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
pyenv: -bash: command not found

[Process completed]
```

**Comment by dannguyen** [comment] 2016-05-17 20:32
Ah nm, maybe it's an issue with pyenv....

**Comment by ocefpaf** [comment] 2016-05-18 14:41
@dannguyen not sure how to mix `pyenv` and `conda-env`. I recommend you to stick with conda-env since that seems to be working properly. You probably had another package that interfered with fiona's requirements.

I am closing this, but feel free to keep discussing/adding message here if you get to the bottom of your original problem.

**Closed by ocefpaf** 2016-05-18 14:41 UTC

**Comment by dannguyen** [comment] 2016-05-22 16:33
@ocefpaf - fair enough, I don't either. For reference's sake, for anyone who stumbles upon this issue via Google, the root cause seems to be fiona being in conflict with libgdal >2.0, which @ocefpaf mentioned here: https://github.com/ioos/conda-recipes/issues/623#issuecomment-161003390

I was able to get Fiona to work on my system with this option:

~~~sh
conda install -c conda-forge fiona "libgdal<2.0"
~~~

**Comment by ocefpaf** [comment] 2016-05-22 19:10
@dannguyen `fiona` from is pinned against `gdal 1.11.4` and our `gdal` is "everything" lib+python bindings+binaries. So you should not be having that issue... Unless something else is pulling `libgdal` from defaults.  I guess we will have to mimic the same nomenclature of the default channel to avoid this.

**Comment by mszell** [comment] 2017-06-15 16:04
Is there a fix for this? I get a similar error when trying to import fiona:
`ImportError: dlopen(/Users/mszell/anaconda/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /Users/mszell/anaconda/lib/libgdal.20.dylib
  Reason: image not found`

Running `conda install -c conda-forge fiona "libgdal<2.0"` didn't help unfortunately. thx

**Comment by ocefpaf** [comment] 2017-06-15 16:08
It is been a while that `fiona` is pinned against `gdal 2`.

Try a new env with:

```shell
conda install -c conda-forge fiona
```

That works.

PS: I strongly recommend reading: http://conda-forge.github.io/docs/conda-forge_gotchas.html#using-multiple-channels

**Comment by mszell** [comment] 2017-06-15 16:44
Thank you for the quick answer!
I have read the linked text and I tried to run that but still the same error. I know nothing about envs though. I just need to run a jupyter notebook script that worked without any problems a few weeks ago - it is suddenly broken due to this fiona import issue. I found the .condarc file, it looks like this:

```
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
ssl_verify: true
```

I tried this too:
`conda config --add channels conda-forge`
but same outcome.

I tried upgrading everything, downgrading fiona (as suggested somewhere), but that also did not help.

Running `conda list` gives me these:
```
Fiona                     1.5.0                     <pip>
fiona                     1.7.7               np111py36_0    conda-forge
..
gdal                      2.2.0               np111py36_0    conda-forge
..
libgdal                   1.11.2                        1 
```

Does that confirm my issue or can help me in some way? Do you think there is a quick fix for this?
 Thank you again!

**Comment by ocefpaf** [comment] 2017-06-15 16:47
You have three channels there. It is not easy to get a consistent environment that way. Here is how to install `fiona` into a new env (and I highly recommend you to check the conda-env docs.) 

```shell
conda create -n MYENVNAME python=3.6 fiona jupyter
source activate MYENVNAME
```

If that is not possible for you I recommend you to remove `conda-forge` from your `condarc` and rely only on `defaults`.

**Comment by mszell** [comment] 2017-06-15 17:06
Great, with an env it finally works! Will read up in more detail on envs. Thx!

**Comment by ocefpaf** [comment] 2017-06-15 21:03
Just some more info on the matter to help you understand what is going on: `fiona` depends on `gdal`, and `gdal` depends on a huge number of c-libs that need to be pinned down to specific versions to avoid software breakage by mixing versions.

The problem is that different channels pin to different versions. That means you need to "stay" within a "trusted/consistent" pinning scheme.

The Anaconda distribution brings a lot of pre-installed software and, even by adding `conda-forge` as the preferred channel (placing it on top of `defaults`), will be hard to get that consistent installation.

We recommend using miniconda and creating envs to "encapsulate" the different cases and get a more stable installation. (Or, like I mention above, if you don't need external channels you can use only `defaults`.)

**Comment by DylanMuir** [comment] 2017-09-08 15:49
Hi, I'm having a similar problem.

I created a new condo environment for `fiona`:
```
conda create --name GIS fiona jupyter
source activate GIS
python
import fiona
```

I then receive the error
```
~/anaconda/envs/GIS/lib/python3.5/site-packages/fiona/collection.py in <module>()
      5 import sys
      6 
----> 7 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
      8 from fiona.ogrext import Session, WritingSession
      9 from fiona.ogrext import (

ImportError: dlopen(/Users/dylan/anaconda/envs/GIS/lib/python3.5/site-packages/fiona/ogrext.so, 2): Library not loaded: @rpath/libjpeg.8.dylib
  Referenced from: /Users/dylan/anaconda/envs/GIS/lib/libgdal.20.dylib
  Reason: image not found
```

I am not using `conda_forge`. I attempted to create an environment using `python=3.6`, but this failed with the message:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - fiona -> cligj 0.2.0 -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
```

**Comment by DylanMuir** [comment] 2017-09-08 16:00
I was able to get a usable environment that satisfied my other needs by selecting only the `condo-forge` channel:
```
conda create --name GIS -c conda-forge python=2.7 fiona jupyter basemap pandas shapely
```

**Comment by liyangxie2019** [comment] 2019-09-05 08:26
,
