### ISSUE TITLE
libpoppler cannot be found when trying to install fiona

### ISSUE THREAD

**Issue by mhearne-usgs** [conda-forge/fiona-feedstock#142] opened 2019-10-18 20:11 UTC
Issue:
E   ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
<br/>
Environment (<code>conda list</code>):
<details>
This is happening in Travis in a CI build. The system information as best I can determine:
Python 3.6.7
fiona version: fiona-1.7.13
pip 19.0.3
poppler-0.81.0
poppler-data-0.4.9

Full error:
Traceback:
gmprocess/io/test_utils.py:6: in <module>
    from gmprocess.event import ScalarEvent
gmprocess/event.py:6: in <module>
    from libcomcat.search import get_event_by_id
../../../miniconda/envs/gmprocess/lib/python3.6/site-packages/libcomcat/search.py:13: in <module>
    from libcomcat.classes import SummaryEvent, DetailEvent
../../../miniconda/envs/gmprocess/lib/python3.6/site-packages/libcomcat/classes.py:22: in <module>
    from libcomcat.utils import HEADERS, TIMEOUT
../../../miniconda/envs/gmprocess/lib/python3.6/site-packages/libcomcat/utils.py:12: in <module>
    import fiona
../../../miniconda/envs/gmprocess/lib/python3.6/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
../../../miniconda/envs/gmprocess/lib/python3.6/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment] 2019-10-19 21:32
@mhearne-usgs can you post the `conda list` and `conda info` for us to debug this?

**Comment by mhearne-usgs** [comment] 2019-10-19 22:38
[condainfo.txt](https://github.com/conda-forge/fiona-feedstock/files/3747253/condainfo.txt)
[condalist.txt](https://github.com/conda-forge/fiona-feedstock/files/3747254/condalist.txt)
@ocefpaf I was able to reproduce this on my laptop (original issue was noticed on Travis, so hard to get this information.) conda info and list output attached as separate text files.

**Comment by ocefpaf** [comment] 2019-10-21 11:33
@mhearne-usgs I see `defaults` on top of `conda-forge` on your `conda-info` and your libgdal is coming from `defaults` on the `conda-list`.

Please see https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge and https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it.

**Comment by mhearne-usgs** [comment] 2019-10-21 14:51
@ocefpaf, still getting same error even after putting conda-forge on top. info/install output attached again.
[conda_list.txt](https://github.com/conda-forge/fiona-feedstock/files/3751439/conda_list.txt)
[conda_info.txt](https://github.com/conda-forge/fiona-feedstock/files/3751440/conda_info.txt)

**Comment by ocefpaf** [comment] 2019-10-21 15:04
I still see packages from defaults. Do you have strict enabled in your .condarc? Are you pinning to a version that does not exist in conda-forge? How are you creating the env?

**Comment by mhearne-usgs** [comment] 2019-10-21 17:42
@ocefpaf neither my package nor any package that I created seems to be pinning to a particular version of libgdal. I have tried deleting defaults from my .condarc and it still grabs libgdal from defaults. Here is the conda create command we're using:

conda create -y -n gmprocess -c conda-forge --channel-priority gcc cython impactutils ipython jupyter libcomcat lxml matplotlib ''\''numpy<1.17'\''' 'obspy>=1.1.1' openpyxl openquake.engine pandas pyasdf pytest pytest-cov 'python>=3.6' pyyaml requests vcrpy

The pinning of numpy and obspy is necessary to avoid a recent change in numpy crashing code in obspy.

**Comment by mhearne-usgs** [comment] 2019-10-22 17:58
@ocefpaf This problem seems to be related to obspy:

https://github.com/conda-forge/obspy-feedstock/blob/master/recipe/meta.yaml#L52

This is (as I think you've noticed before) an old version of proj4, and it causes conflicts when I try to do something like:

conda create -n testgeo python=3.6 fiona obspy=1.1.1

I think we'll try contacting the obspy team to see if they can remove this dependency, since it seems tied to Basemap, which as we all know is on it's way out.

**Comment by ocefpaf** [comment] 2019-10-23 12:19
> @ocefpaf This problem seems to be related to obspy:
> 
> [conda-forge/obspy-feedstock:recipe/meta.yaml@`master`#L52](https://github.com/conda-forge/obspy-feedstock/blob/master/recipe/meta.yaml#L52) [](/conda-forge/obspy-feedstock/blob/HEAD@{2019-10-22T17:58:30Z}/recipe/meta.yaml#L52)


Yes. `obspy` is lagging behind :-/

Closing this b/c the problem is not with `fiona`.

**Closed by ocefpaf** 2019-10-23 12:19 UTC
