### ISSUE TITLE
Not quite deterministic segfault (11) or bus error (10) when writing GeoPackage 

### ISSUE THREAD

**Issue by chryss** [conda-forge/fiona-feedstock#41] opened 2017-04-16 20:20 UTC
I believe this is the same bug that was filed on the main Fiona repository here: https://github.com/Toblerity/Fiona/issues/407 . The behavior is triggered by the code in that bug report:

    schema = {'geometry': 'Point', 'properties': [('title', 'str')]}     
    crs = {'init': 'EPSG:4326'}    
    with fiona.open(os.path.join(tmpdir, 'foo.gpkg'), 'w', layer='bar_foo', driver='GPKG',     
    schema=schema, crs=crs) as d:    
        d.writerecords([{    
                        'geometry': {'type': 'Point', 'coordinates': [0.0, 0.0]},    
                        'properties': {'title': 'One'}}])    
        d.writerecords([{    
                        'geometry': {'type': 'Point', 'coordinates': [2.0, 3.0]},    
                        'properties': {'title': 'Two'}}])    

My platform is OS X (10.11.6) and Python 2.7 from Anaconda. I use GeoPandas to read or generate geospatial vector data, and to write it out. I use GeoPackage as my intermediary data product format. GeoPandas uses Fiona under the hood. When writing a GeoPackage in a Jupyter notebook, the file gets generated (though with very large datasets, it may not be complete); however, the kernel restarts. Running it from a script on the command line revealed a segmentation fault (11). Re-running the script  multiple times is leading to one of these outcomes: no error (about 20% of times), segmentation fault (11) (about 40% of times), bus error (10) (about 40% of times). 

This is in a virtual environment that was generated, fresh using `conda install  -c conda-forge geopandas`, that is, all dependencies were installed from conda-forge (to avoid library hell type situations). (The error initially happened in an environment for which most libraries came from standard `conda install ...`, except geopandas and a small number of other packages from conda-forge.) 

Relevant library versions:

    descartes:          1.1.0-py27_0       conda-forge
    expat:              2.1.0-2            conda-forge
    fiona:              1.7.5-np112py27_0  conda-forge
    gdal:               2.1.3-np112py27_3  conda-forge
    geopandas:          0.2.1-py27_3       conda-forge
    geos:               3.5.1-1            conda-forge
    libspatialite:      4.3.0a-14          conda-forge
    numpy:              1.12.1-py27_0                 
    pandas:             0.19.2-np112py27_1 conda-forge
    proj4:              4.9.3-3            conda-forge
    pyproj:             1.9.5.1-py27_0     conda-forge
    shapely:            1.5.17-np112py27_2 conda-forge

The backtrace from lldb looks like this:

  * thread #1: tid = 0x0000, 0x000000010db1629e libgdal.20.dylib`OGRSpatialReference::Release() + 62, stop reason = signal SIGSTOP    
    * frame #0: 0x000000010db1629e libgdal.20.dylib`OGRSpatialReference::Release() + 62    
    frame #1: 0x000000010db9620f libgdal.20.dylib`OGRGeomFieldDefn::~OGRGeomFieldDefn() + 79    
    frame #2: 0x000000010db96235 libgdal.20.dylib`OGRGeomFieldDefn::~OGRGeomFieldDefn() + 21    
    frame #3: 0x000000010db96258 libgdal.20.dylib`OGRGeomFieldDefn::~OGRGeomFieldDefn() + 24    
    frame #4: 0x000000010db0ab74 libgdal.20.dylib`OGRFeatureDefn::~OGRFeatureDefn() + 308    
    frame #5: 0x000000010db0abc5 libgdal.20.dylib`OGRFeatureDefn::~OGRFeatureDefn() + 21    
    frame #6: 0x000000010db0abe8 libgdal.20.dylib`OGRFeatureDefn::~OGRFeatureDefn() + 24    
    frame #7: 0x000000010db0aca1 libgdal.20.dylib`OGRFeatureDefn::Release() + 65    
    frame #8: 0x000000010d765a48 libgdal.20.dylib`OGRGeoPackageLayer::~OGRGeoPackageLayer() + 200    
    frame #9: 0x000000010d76f3d1 libgdal.20.dylib`OGRGeoPackageTableLayer::~OGRGeoPackageTableLayer() + 721    
    frame #10: 0x000000010d770545 libgdal.20.dylib`OGRGeoPackageTableLayer::~OGRGeoPackageTableLayer() + 21    
    frame #11: 0x000000010d770598 libgdal.20.dylib`OGRGeoPackageTableLayer::~OGRGeoPackageTableLayer() + 24    
    frame #12: 0x000000010d74e8aa libgdal.20.dylib`GDALGeoPackageDataset::~GDALGeoPackageDataset() + 986    
    frame #13: 0x000000010d74feb5 libgdal.20.dylib`GDALGeoPackageDataset::~GDALGeoPackageDataset() + 21    
    frame #14: 0x000000010d74ff08 libgdal.20.dylib`GDALGeoPackageDataset::~GDALGeoPackageDataset() + 24    
    frame #15: 0x000000010d18bb2b libgdal.20.dylib`GDALClose + 155    
    frame #16: 0x000000010c9c432f ogrext.so`__pyx_pw_5fiona_6ogrext_7Session_7stop + 31    
    frame #17: 0x000000010c35add0 libpython2.7.dylib`PyEval_EvalFrameEx + 29136    
    frame #18: 0x000000010c3600b2 libpython2.7.dylib`fast_function + 274    
    frame #19: 0x000000010c35adb3 libpython2.7.dylib`PyEval_EvalFrameEx + 29107    
    frame #20: 0x000000010c3538f2 libpython2.7.dylib`PyEval_EvalCodeEx + 1538    
    frame #21: 0x000000010c2de43c libpython2.7.dylib`function_call + 364    
    frame #22: 0x000000010c2b8333 libpython2.7.dylib`PyObject_Call + 99    
    frame #23: 0x000000010c2c55b6 libpython2.7.dylib`instancemethod_call + 182    
    frame #24: 0x000000010c2b8333 libpython2.7.dylib`PyObject_Call + 99    
    frame #25: 0x000000010c2b2b97 libpython2.7.dylib`PyObject_CallFunctionObjArgs + 359    
    frame #26: 0x000000010c35ce5d libpython2.7.dylib`PyEval_EvalFrameEx + 37469    
    frame #27: 0x000000010c3538f2 libpython2.7.dylib`PyEval_EvalCodeEx + 1538    
    frame #28: 0x000000010c2de43c libpython2.7.dylib`function_call + 364    
    frame #29: 0x000000010c2b8333 libpython2.7.dylib`PyObject_Call + 99    
    frame #30: 0x000000010c35b901 libpython2.7.dylib`PyEval_EvalFrameEx + 32001    
    frame #31: 0x000000010c3538f2 libpython2.7.dylib`PyEval_EvalCodeEx + 1538    
    frame #32: 0x000000010c360015 libpython2.7.dylib`fast_function + 117    
    frame #33: 0x000000010c35adb3 libpython2.7.dylib`PyEval_EvalFrameEx + 29107    
    frame #34: 0x000000010c3538f2 libpython2.7.dylib`PyEval_EvalCodeEx + 1538    
    frame #35: 0x000000010c3532e6 libpython2.7.dylib`PyEval_EvalCode + 54    
    frame #36: 0x000000010c382254 libpython2.7.dylib`PyRun_FileExFlags + 164    
    frame #37: 0x000000010c381dd1 libpython2.7.dylib`PyRun_SimpleFileExFlags + 769    
    frame #38: 0x000000010c397a12 libpython2.7.dylib`Py_Main + 3154    
    frame #39: 0x000000010c2a5f24 python`start + 52    

The issue does not occur when I write a GeoPackage file directly using gdal/ogr (no Fiona). It doesn't occur if I write an ESRI Shapefile or a GeoJSON file with Fiona.

**Comment by ocefpaf** [comment] 2017-04-17 11:16
>  The behavior is triggered by the code in that bug report:

It is kind of hard for us to navigate other bug reports with our limited time. Could you put together a [sscce](http://sscce.org/) so we can try to debug this?

**Comment by chryss** [comment] 2017-04-18 05:36
Does the code snippet I posted right at the top (after the sentence you posted) not suit your need? I guess once could add the necessary imports. This version should be completely self-contained:

    import os, fiona
    schema = {'geometry': 'Point', 'properties': [('title', 'str')]}     
    crs = {'init': 'EPSG:4326'}    
    with fiona.open(os.path.join(tmpdir, 'foo.gpkg'), 'w', layer='bar_foo', driver='GPKG',     
    schema=schema, crs=crs) as d:    
        d.writerecords([{    
                        'geometry': {'type': 'Point', 'coordinates': [0.0, 0.0]},    
                        'properties': {'title': 'One'}}])    
        d.writerecords([{    
                        'geometry': {'type': 'Point', 'coordinates': [2.0, 3.0]},    
                        'properties': {'title': 'Two'}}])

**Comment by ocefpaf** [comment] 2017-04-18 11:50
Reading your message above and navigating the issues I had the impression that I needed more to reproduce it. A I cannot reproduce the error you reported above with that snippet :unamused: 
Everything works for me on Linux (I don't have a Mac.)

**Comment by ocefpaf** [comment] 2017-04-19 11:53
@chryss take a look at https://github.com/Toblerity/Fiona/issues/441 it seems that it is not a packaging issue so I am closing this. Let's keep an eye upstream and hopefully this will be fixed soon.

**Closed by ocefpaf** 2017-04-19 11:53 UTC

**Comment by chryss** [comment] 2017-04-19 15:22
Yes, thanks.
