### ISSUE TITLE
error in geopandas due to fiona

### ISSUE THREAD

**Issue by waqarmalik** [conda-forge/fiona-feedstock#44] opened 2017-05-20 02:29 UTC
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-c9ee6bd24dbc> in <module>()
----> 1 import geopandas

/home/wmalik/miniconda3/lib/python3.5/site-packages/geopandas/__init__.py in <module>()
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

/home/wmalik/miniconda3/lib/python3.5/site-packages/geopandas/io/file.py in <module>()
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 from shapely.geometry import mapping

/home/wmalik/miniconda3/lib/python3.5/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68 
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

/home/wmalik/miniconda3/lib/python3.5/site-packages/fiona/collection.py in <module>()
      7 
      8 from fiona import compat
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import (

ImportError: libnetcdf.so.7: cannot open shared object file: No such file or directory
```

Here are the version information. 
```
# packages in environment at /home/wmalik/miniconda3:
#
fiona                     1.7.6               np112py35_0    conda-forge

>> conda list netcdf
# packages in environment at /home/wmalik/miniconda3:
#
h5netcdf                  0.3.1                    py35_0    conda-forge
libnetcdf                 4.4.1.1                       4    conda-forge
netcdf4                   1.2.7               np112py35_0    conda-forge
```

**Comment by ocefpaf** [comment] 2017-05-21 03:56
Can you ensure that the `conda-forge` is on top of `defaults` in your `.condarc`? (Looks like it b/c all the packages are from `conda-forge`). Then can you try installing it into a separate env like:

```shell
conda create -n TEST geopandas -c conda-forge
source activate TEST
python -c "import geopandas; print(geopandas.__version__)"
```

**Comment by ocefpaf** [comment] 2017-06-05 17:36
I cannot reproduce this so I am closing it. Please let me know if you are still experiencing this. Also, take a look at http://conda-forge.github.io/docs/conda-forge_gotchas.html#using-multiple-channels

**Closed by ocefpaf** 2017-06-05 17:36 UTC
